### ISSUE TITLE
Error: Got unexpected extra argument (300)

### ISSUE THREAD

**Issue by asomervell** [donaldpiret/ecs-deploy#1]
Gidday, using this for an open source project, with the following config:

```
    - name: ECS Deployment
      uses: donaldpiret/ecs-deploy@v0.0.1
      with:
        cluster: vly-alpha-ECSCluster
        target: vly-alpha
        image: vly-alpha:latest
```

And I get the following, not sure how i'm introducing an extra param or getting the commands wrong?

```
Performing deploy
Command run: ecs deploy vly-alpha-ECSCluster vly-alphaTargetGroup -i vly-alpha:latest --timeout 300
Usage: ecs deploy [OPTIONS] CLUSTER SERVICE

Error: Got unexpected extra argument (300)
```

Thanks,

**Comment by donaldpiret** [comment]
Hey @asomervell, the image parameter requires both the name of the container to update as well as the image, eg. in your case it would be (if your container name was "app"):

```
    - name: ECS Deployment
      uses: donaldpiret/ecs-deploy@v0.0.1
      with:
        cluster: vly-alpha-ECSCluster
        target: vly-alpha
        image: app vly-alpha:latest
```

Hope this helps.
