### ISSUE TITLE
Include example pipline with aws credentials action

### ISSUE THREAD

**Issue by MarshallAsch** [donaldpiret/ecs-deploy#21]
Would you be able to include a full example action using the [aws-actions/configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) action  in a workflow file? 

I have tried using them together and repeatedly get issues with authentication failures

```
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ca-central-1
          role-to-assume: role::arn:aws:iam::*** :role/github_webapp_frontend_dev
      - name: Deploy new container to ECS
        uses: donaldpiret/ecs-deploy@v0.3.0
        with:
          cluster: "myCluster"
          target: "myService"
```

Output: 

```
Run aws-actions/configure-aws-credentials@v1
  with:
    aws-region: ca-central-1
    role-to-assume: arn:aws:iam::***:role/github_webapp_frontend_dev

Run donaldpiret/ecs-deploy@v0.3.0
  with:
    cluster: myCluster
    target: myService
    action: deploy
    timeout: 300
  env:
    AWS_DEFAULT_REGION: ca-central-1
    AWS_REGION: ca-central-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    AWS_SESSION_TOKEN: ***

Performing deploy
Command run: ecs deploy myCluster myService --timeout 300
An error occurred (AccessDeniedException) when calling the DescribeServices operation: User: arn:aws:sts::***:assumed-role/github_webapp_frontend_dev/GitHubActions is not authorized to perform: ecs:DescribeServices on resource: arn:aws:ecs:ca-central-1:***:service/myCluster/myService because no identity-based policy allows the ecs:DescribeServices action

```

When runnign it locally using [fabfuel/ecs-deploy](https://github.com/fabfuel/ecs-deploy)

```
ecs deploy -r arn:aws:iam::***:role/github_webapp_frontend_dev myCluster myService 
```

It works perfectly fine.
